### ISSUE TITLE
Bug on websocket seedlink request handling - Data unmasking done twice

### ISSUE THREAD

**Issue by Ale77m** [EarthScope/ringserver#60]
In 4.0.0 release, a websocket seedlink request is not properly handled by the server. It seems that data unmasking, if a mask was supplied as websocket, is done twice: 1) in RecvLine function, clients.c lines 1062-1066, 2) in RecvData function, clients.c lines 893-903.

Commenting lines 893-903 in clients.c file seems to fix this issue.

**Comment by Ale77m** [comment]
Update: Commenting lines 893-903 in clients.c file seems to fix the initial handshake, but introduces other issues.

**Comment by crotwell** [comment]
I think I am seeing similar things. Commenting out those lines, I am able to connect, but the server seems to garble the sent text. For example, sending 
```
STATION JSC CO
SELECT 00HHZ.D
```
but on the server I see:
```
Thu Dec 05 16:05:08 2024 - Incoming connection: 127.0.0.1 port 47712
Thu Dec 05 16:05:08 2024 - Client connected [6371]: localhost [127.0.0.1] port 47712
Thu Dec 05 16:05:08 2024 - [localhost] Received HTTP request /seedlink
Thu Dec 05 16:05:08 2024 - [localhost] Received WebSocket SeedLink request
Thu Dec 05 16:05:09 2024 - [localhost] Unrecognized command: TSELCT d0HH.D
Thu Dec 05 16:05:19 2024 - [localhost] Timeout receiving data
Thu Dec 05 16:05:19 2024 - Client disconnected: localhost
```

Other times I see things like this:
```
Thu Dec 05 16:01:51 2024 - Incoming connection: 127.0.0.1 port 58500
Thu Dec 05 16:01:51 2024 - Client connected [6371]: localhost [127.0.0.1] port 58500
Thu Dec 05 16:01:51 2024 - [localhost] Received HTTP request /seedlink
Thu Dec 05 16:01:51 2024 - [localhost] Received WebSocket SeedLink request
Thu Dec 05 16:01:51 2024 - [localhost] Error, the WebSocket FIN flag is not set and fragmentation is not supported
Thu Dec 05 16:01:51 2024 - Client disconnected: localhost
```

**Comment by Ale77m** [comment]
[ringserver_log.log](https://github.com/user-attachments/files/18036544/ringserver_log.log)

I did some further debug, adding some printf lines and modifying some code lines (files: http.c, clients.c, ecc).

**Comment by chad-earthscope** [comment]
Thanks @Ale77m and @crotwell.

I think I've got this fixed in the `develop` branch.  If  you could test and verify it's working for you I'd appreciate it.

**Comment by crotwell** [comment]
I was able to seed seedlink3 working with the develop branch of the new ringserver, so seems websocket stuff working. Perhaps a separate issue, but I am still getting an error parsing a miniseed record via datalink over websocket. I'll need to dig a bit more to see what the issue is. My datalink test code works for old ringserver but fails for v4 when parsing a datalink packet containing miniseed.

**Comment by chad-earthscope** [comment]
> Perhaps a separate issue, but I am still getting an error parsing a miniseed record via datalink over websocket.

@crotwell I think this is fixed now.  I don't think that had anything particularly to do with WebSocket, but related to the changes I made in the previous commit to address masking and variable terminators for commands.

**Comment by crotwell** [comment]
Yes, datalink seems to work now, at least with `FDSN:` style ids.

For datalink with old style ids it doesn't find any streams. So this works:
```
Send: MATCH FDSN:CO_JSC_00_H_H_./MSEED 
start datalink at : 2024-12-15T14:20:12.776Z 
Send: POSITION AFTER 1734272412776000 undefined 
Send: STREAM
```
but this fails to match any streams:
```
Send: MATCH CO_JSC_00_HH./MSEED 
```

The release notes sound like old style match patterns for datalink should still work. Am I misunderstanding?

> All legacy stream IDs for miniSEED of the form: NN_SSSSS_LL_CCC/MSEED will be converted to FDSN Source ID form: FDSN:NN_SSSSS_LL_C_C_C/MSEED.

**Comment by crotwell** [comment]
@chad-earthscope fyi, was able to seedlink4 from websocket successfully

**Comment by Ale77m** [comment]
Hi, I just tried the latest version from develop branch, but I still
receive  "Error, the WebSocket FIN flag is not set and fragmentation is not
supported" which comes from "Variable command terminators" issue.

What I did was the following:

- clone the git repository
- git checkout develop
- compile & test the application.

Am I missing something?



Il giorno dom 15 dic 2024 alle ore 18:06 Chad Trabant <
***@***.***> ha scritto:

**Comment by chad-earthscope** [comment]
Hi @Ale77m 

The first 2 steps of your process seems correct to me.

> - compile & test the application.

How did you test?

**Comment by Ale77m** [comment]
Hi Chad,

I tested the application with our web interface, which embeds a seedlink
over websocket client based on
https://github.com/crotwell/seisplotjs-seedlink . This client works
correctly with ringserver 2018 and 2020 releases, but seems not compatible
with 4.0.0 release and the current developer branch. I did not make any
further investigation and I'm not sure if the problem is caused by the
client side adding one or more command terminators after the 0x0D.

Il giorno mar 17 dic 2024 alle ore 02:16 Chad Trabant <
***@***.***> ha scritto:

**Comment by crotwell** [comment]
I am not sure why that javascript would not work with the new ringserver, but that version of seisplotjs is really old and should no longer be used. The newer version of seisplotjs (v3.1.4) here: 
https://github.com/crotwell/seisplotjs

I am working on a new release to support new datalink 1.1. and seedlink4 that may be of interest. See the dev branch. Hopefully will be able to push out a new release soon.

**Comment by Ale77m** [comment]
Our software was initially developed 5 years ago on the seisplotjs version available at that time and we haven't upgraded it to the newer version since, meanwhile, we deployed the same ringserver version from 2018.

BTW, I just wrote this tiny python test script:

**Comment by chad-earthscope** [comment]
@Ale77m 

Thanks for the test script.  On macOS, using Python 3.13.1, websocket_client-1.8.0 from PyPI, and guessing at the indentation of the script, I had no problems.

Here is my version of your script:

```Python
from websocket import create_connection
import time
ws = create_connection("ws://127.0.0.1:18000/seedlink") #change this address according to your ringserver configuration

while 1:
  print("Sending HELLO")
  print(ws.send("HELLO\r"))

  result = ws.recv()
  print("Received '%s'" % result)

  print("Sending STATION * *")
  print(ws.send("STATION * *\r"))
  result = ws.recv()
  print("Received '%s'" % result)

  print("Sending SELECT 00BHZ")
  print(ws.send("SELECT 00BHZ\r"))
  result = ws.recv()
  print("Received '%s'" % result)

  print("Sending SELECT 10BHZ")
  print(ws.send("SELECT 10BHZ\r"))
  result = ws.recv()
  print("Received '%s'" % result)

  print("Sending DATA")
  print(ws.send("DATA\r"))

  result = ws.recv()
  print("Received '%s'" % result)

  print("Sending END")
  print(ws.send("END\r"))
  print("Received '%s'" % result)

  while 1:
    result = ws.recv()
    print("Received '%s'" % result)

ws.close()
```

and the results:
```Console
❯ python3 wstest.py
Sending HELLO
12
Received 'b'SeedLink v4.0 (RingServer/4.0.0) :: SLPROTO:4.0 SLPROTO:3.1 CAP WS:13\r\nRing Server\r\n''
Sending STATION * *
18
Received 'b'OK\r\n''
Sending SELECT 00BHZ
19
Received 'b'OK\r\n''
Sending SELECT 10BHZ
19
Received 'b'OK\r\n''
Sending DATA
11
Received 'b'OK\r\n''
Sending END
10
Received 'b'OK\r\n''
Received 'b'SL3D482F151572R AAK  10BHZII\x07\xe8\x01`\x17\x02\x0c\x00\x13Q\x01\xe4\x00(\x00\x01\x00 \x00\x02\x00\x00\x00\x00\x00@\x000\x03\xe8\x008\x0b\x01\t\x00\x03\xe9\x00\x00d$\x00\x07\x03\xf7\xfd\xff\x00\x00\x07:\x00\x00\x07\xd5\x02,\xff\x04\x1dG\xe3\x03\x05I\x15\xbc\xee\x0c\'\t/\x11\x16\r6\xec\xd5A\x04x\x8eJ\x035\xc4\x0b\xf4\xe6\x143\x0f\xb7\xf2\xbf\x16V\xcfW\x00\xd0\xb3k) \xdf\xf3?}w\xff5\xdc\x84\xa9!\xf7[\x85?\x97\\)\n\xf7\xda\xf6>\xcf\x8b*/\xccr)\xd7\xe3\xed\xfd\x12\xfa\xd0\xeb\x03\x83\x97\xb0\xcc\xf0\x12\xf3!\xbf!E&\x87\x8d)\x00\xe6\x8b\xc4\x03\xb6\xf0~&\xb4\xd1\xf5?\xf7\xff\xff\x06\x12\xafBl6\x8f\xdf:\x08QL\x17\x0bsV\x0e\xfd\x122\x05\x13#\x0e4\x04\xd4z\x07w\xa0\xcf\x00)v\xbc?h\x81L\x05\x08\xa2\x0f\x1b\xdb7\x1b\x04\xddW\x00\x16g\xff\x13\x16\xd4\xb6\x83\x17\xfd\xf7\xfd\x14\r\x00\x07%%\xf8\x00:\xe5\xa4\x85\x06L\xae\x88\x17$Q8\x0ewY\r-\x0f\xf4\xfa\t/T\x97\'\xc8k\xf9*\t\xda\xec;\x14\x0fy.\xfcM\xba:\xf3\x8a\'\x05+~#\xff!\xeb\xdc?u_\xf7\x047=\xaf#\x08\r72\xb3\xe42\xd2\xe8\xfa\xe98\x1a\xc97\xe6\xdc\x0e\x03\xd1\xe0\x04\xfd\xd3\xeb\x12\xff\xdf\xe5\xf6\xea/\x14\x08`6\xf8\xa0\xae-\xe3l\xc5<0\x89\xae\xf6\x19\x0e\xd70\'\xcd??\xf5}U\x18p(3\x1e\x13P\xb1\x04?\xbb\xc2\x1b\xe7e\x01nD\xa8\x0e,\x0e\xeb\x07$\x11\x04\x17\x0b\x0f%\x17\x05\x05\x97\x97\x1f\x0c\xa7\x8f \x19\x08\x08\x05\x1f!\x07\x1b%\xf9\x01\x1c\x14%\x11\xec\x04 \x11?]\xfdU\x02P\xe0\x9a\x19\xc7\x15\x1f\x12\xf4\x04>\xf4\x08"\x03\xdb\x01\x18\xf9J\xces\x86\x05\xed\xda\xfd\x1e\xf7_\xe7,8Y\xa9.\xacSy\xef\xdf\xe3\x04\x03\xf2\xfa\xe9\xde\xfb\xfd\xfa\xf7\xe9\xf5\xf1\xdd\xf8#\x03''
Received ...
```

I did the same test on a ubuntu linux machine with pPython 3.12.3 and doing a fresh build:
```
git clone https://github.com/EarthScope/ringserver
cd ringserver
git checkout develop
make -j
mkdir ring
./ringserver -Rd ring -L 18000
```

and the script also worked here without errors.

**Comment by Ale77m** [comment]
Hi Chad,

I tried again the whole clone/compile/test procedure and I got it working
fine with the test script but not with our web interface. I guess this is
an incompatibility between the 4.0.0 ringserver release and the old
seisplotjs, due to unwanted termination bytes. I will consider porting the
web GUI to the latest seisplotjs, but in the meanwhile I will use my
modified ringserver version which works correctly for me.

Regards.

Il giorno mar 17 dic 2024 alle ore 23:22 Chad Trabant <
***@***.***> ha scritto:

**Comment by chad-earthscope** [comment]
> I guess this is an incompatibility between the 4.0.0 ringserver release and the old seisplotjs, due to unwanted termination bytes.

Ah, I think I understand.  You're saying that the old seisplotjs sends extra, more than 2, termination characters?  

If so, that's odd client behavior but _should_ be allowed (within reason, otherwise you end up accepting infinite terminators and invite a DoS).  I've played with a fix today, but it still needs some work.

**Comment by Ale77m** [comment]
As far as I understand fro your code, you filter out 0x0D and/or 0x0A additional terminators (at least up to a limit of 10 terminators in row, which is an adequate limit IMHO). Unfortunately, what I saw while debugging the master branch were "spurious" terminators bytes: I mean values that are not supposed to be terminators. In this case, they are interpreted as a start of a new WS packet and they rise the FIN flag error.

**Comment by chad-earthscope** [comment]
I found an issue that did not allow the extra terminators, which should be interpreted as empty commands, in WebSocket mode.  This is included in v4.0.1.
